version: '2'

services:
  sentiment:
    command: "sh start_app.sh"
    image: python
    working_dir: /project
    volumes:
      - ./sentiment-analysis:/project
    ports:
      - 5000:5000

  tweets:
    build: ./tweets
    command: "bash -c 'yarn && yarn start'"
    volumes:
      - ./tweets:/project
    links:
      - postgres
      - sentiment
    environment:
     - DATABASE_HOST=postgres
    ports:
     - 8000:8000

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=tweets
    ports:
      - 5432:5432
